---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.15.0

overrides:
- image: fluxcd/source-controller:v0.33.0
  newImage: projects.registry.vmware.com/tce/fluxcd-source-controller:v0.33.0
